#!/bin/bash
# author: kevinkirst
set -euo pipefail
	# 'set [+-]e' -> exits if any command has a non zero exit status
	# 'set [+-]u' -> exits if an undefined variable is referenced 
		# requires ':-' to be placed after unbound variables ('${1}' becomes '${1:-}')
	# 'set [+-]o pipefail' -> prevents error in a pipeline from being masked
IFS=$'\n\t'
	# Internal Field Separator -> set to 'new line' and 'tab'

# changelog
#	v1.0 - 
#		 - 

# =-= VARIABLES =-= #
MODULE=$(basename $0)
source ./lib/config.cfg
HI="sup"

# =-= FUNCTIONS =-= #
function help {
	echo "$MODULE: $MODULE [--help]
	[description]
	
	Options:
		--help		print the help page"
	exit 0
}

# =-= MAIN =-= #
if [[ "${1:-}" = "--help" ]]; then help; fi
if ! [[ -z "${1:-}" ]]; then help; fi
# vVv main script code vVv
echo -e $CLR_GREEN "$HI" $CLR_DEFAULT
echo -e $CLR_RED $0 $CLR_DEFAULT
echo $MODULE