#!/bin/bash
# author:kevinkirst
# runs on system start-up to set up critical functionality and configurations

set -uo pipefail
	# 'set [+-]e' -> exits if any command has a non zero exit status
	# 'set [+-]u' -> exits if an undefined variable is referenced 
		# requires ':-' to be placed after unbound variables ('${1}' becomes '${1:-}')
	# 'set [+-]o pipefail' -> prevents error in a pipeline from being masked
IFS=$'\n\t'
	# Internal Field Separator -> set to 'new line' and 'tab'

# service idea came from:
# https://wiki.archlinux.org/title/backlight#Backlight_is_always_at_full_brightness_after_a_reboot_with_amdgpu_driver
# adding $HOME/bin to $PATH
PATH="/home/kirst/bin:$PATH"
LOG="/home/kirst/Desktop/always_me_test"

# sleep 10
# libreoffice --writer

echo test >> $LOG
echo $PATH >> $LOG
