#!/bin/bash
# author: kevinkirst

# changelog
#	v1.0 - pauses the prompt
#		 - can accept strings as parameter
#		 - 

# =-= USAGE =-= #
# source $DIR_LIB/pause "<pause message>"
# OR
# source $PAUSE "<pause message>"

# =-= VARIABLES =-= #
# $MESSAGE gets all passed strings as it's value or defaults to empty string
MESSAGE=${@:-}

# =-= FUNCTIONS =-= #

# =-= MAIN =-= #
# vVv main script code vVv
# if message is not empty append ": " to it
if [ ! -z "$MESSAGE" ]; then
	MESSAGE="${MESSAGE}: "
fi
# pauses prompt with message if there's any
read -s -n 1 -p "${MESSAGE}"