#!/bin/bash
# author: kevinkirst
set -euo pipefail
	# 'set [+-]e' -> exits if any command has a non zero exit status
	# 'set [+-]u' -> exits if an undefined variable is referenced 
		# requires ':-' to be placed after unbound variables ('${1}' becomes '${1:-}')
	# 'set [+-]o pipefail' -> prevents error in a pipeline from being masked
IFS=$'\n\t'
	# Internal Field Separator -> set to 'new line' and 'tab'

# =-= VARIABLES =-= #
# script's filename
MODULE=$(basename $0)
# ${NUMERALS} -> integer interval
NUMERALS='^[0-9]+$'
# user provided percentage of sun power, default is '100' if no value is provided
SUN_PERCERT="${1:-100}"
# ACPI interface directory
ACPI_DIRECTORY="/sys/class/backlight/acpi_video0"
# ACPI interface file - 'brightness' located inside $ACPI_DIRECTORY
ACPI_FILE="brightness"

# =-= FUNCTIONS =-= #
function help {
	echo "$MODULE: $MODULE [--help] (1..100)
	set brightness level of laptop screens
	
	Options:
		(1..100)	range, number which sets the screen's brightness percentage
					must be a value between 1..100 - default: 100
		--help		print this help page
	
	Pre-requisites
		run the command $ nano /etc/default/grub
		swap the following line:
			GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
		for:
			GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_backlight=video"
		reboot the machine.

		after reboot the directory '/sys/class/backlight/acpi_video0' will be created
		change group of the 'brightness' file located in this folder from root to [user_group] using:
			$ chgrp -v [user_group] brightness
		add write permissions to [user_group] group for 'brightness' file
			$ chmod 664 brightness
		
		pre-requisites have to be done only once, most likely using sudo.
"
	exit 0
}

# =-= MAIN =-= #
# if $1 is '--help' show help
if [[ "${SUN_PERCERT}" = "--help" ]]; then help; fi
# if $1 not a numeral show help
if ! [[ "${SUN_PERCERT}" =~ ${NUMERALS} ]]; then help; fi
# if $1 not between 1 and 100 show help
if ! (( "${SUN_PERCERT}" > 0 && "${SUN_PERCERT}" < 101)); then help; fi
# set new brightness
echo ${SUN_PERCERT}> ${ACPI_DIRECTORY}/${ACPI_FILE}